ridgeline moved and render js refactored
plotthatstory/viz_co pull request #12
Opened 2021-11-24 15:45 UTC by plotthatstory

2021-11-25 07:12 UTC, shreshthmohan requested changes

2021-11-25 07:12 UTC, shreshthmohan commented on src/charts/ridgeline/validateAndRender.js
> +  xField: [],
shouldNotBeBlank validation?

2021-11-25 07:12 UTC, shreshthmohan commented on demo/src/ridgeline/index.js
> +  colorRange: d3.schemeTableau10,
fix eslint error. add d3 to global (see first line)

2021-11-25 07:12 UTC, shreshthmohan commented on src/charts/ridgeline/render.js
> +    widgetsRight,
fix eslint error (declared but never used)

2021-11-26 03:46 UTC, plotthatstory commented on src/charts/ridgeline/validateAndRender.js
> +  xField: [],
I left it blank intentionally but cannot remember why. Probably a mistake. Made it shouldNotBeBlank

2021-11-26 03:47 UTC, plotthatstory commented on demo/src/ridgeline/index.js
> +  colorRange: d3.schemeTableau10,
Fixed
`/* global viz, d3 */`

2021-11-26 03:49 UTC, plotthatstory commented on src/charts/ridgeline/render.js
> +    widgetsRight,
Still returning widgets right from setupChartArea fucntion. Removed it when the function is called from renderChart.
We can move the setupCartArea function to general utils.

2021-11-26 05:01 UTC, merged